In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
%run "../notebooks/cargar_df.ipynb"

plt.style.use('default')
sns.set(style="whitegrid")
pd.options.display.float_format = '{:20,.2f}'.format

In [2]:
data_folder  = "../data/"

In [3]:
train = pd.read_csv(data_folder + "Entrenamieto_ECI_2020.csv")

### Analisis del set

In [4]:
#Obtengo la info basica del set de datos 
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16947 entries, 0 to 16946
Data columns (total 52 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  16947 non-null  int64
 1   Region                              16947 non-null  object
 2   Territory                           16947 non-null  object
 3   Pricing, Delivery_Terms_Quote_Appr  16947 non-null  int64
 4   Pricing, Delivery_Terms_Approved    16947 non-null  int64
 5   Bureaucratic_Code_0_Approval        16947 non-null  int64
 6   Bureaucratic_Code_0_Approved        16947 non-null  int64
 7   Submitted_for_Approval              16947 non-null  int64
 8   Bureaucratic_Code                   16947 non-null  object
 9   Account_Created_Date                16947 non-null  object
 10  Source                              16947 non-null  object
 11  Billing_Country                     16947 non-null  object
 12  Account_Name                        16947 non-null  object
 13  Opportunity_Name                    16947 non-null  object
 14  Opportunity_ID                      16947 non-null  int64
 15  Sales_Contract_No                   16947 non-null  object
 16  Account_Owner                       16947 non-null  object
 17  Opportunity_Owner                   16947 non-null  object
 18  Account_Type                        16947 non-null  object
 19  Opportunity_Type                    16947 non-null  object
 20  Quote_Type                          16947 non-null  object
 21  Delivery_Terms                      16947 non-null  object
 22  Opportunity_Created_Date            16947 non-null  object
 23  Brand                               16947 non-null  object
 24  Product_Type                        16947 non-null  object
 25  Size                                16947 non-null  object
 26  Product_Category_B                  16947 non-null  object
 27  Price                               16947 non-null  object
 28  Currency                            16947 non-null  object
 29  Last_Activity                       16947 non-null  object
 30  Quote_Expiry_Date                   16947 non-null  object
 31  Last_Modified_Date                  16947 non-null  object
 32  Last_Modified_By                    16947 non-null  object
 33  Product_Family                      16947 non-null  object
 34  Product_Name                        16947 non-null  object
 35  ASP_Currency                        16947 non-null  object
 36  ASP                                 13738 non-null  float64
 37  ASP_(converted)_Currency            16947 non-null  object
 38  ASP_(converted)                     13738 non-null  float64
 39  Planned_Delivery_Start_Date         16947 non-null  object
 40  Planned_Delivery_End_Date           16947 non-null  object
 41  Month                               16947 non-null  object
 42  Delivery_Quarter                    16947 non-null  object
 43  Delivery_Year                       16947 non-null  int64
 44  Actual_Delivery_Date                16947 non-null  object
 45  TRF                                 16947 non-null  int64
 46  Total_Amount_Currency               16947 non-null  object
 47  Total_Amount                        16888 non-null  float64
 48  Total_Taxable_Amount_Currency       16947 non-null  object
 49  Total_Taxable_Amount                16947 non-null  float64
 50  Stage                               16947 non-null  object
 51  Prod_Category_A                     16947 non-null  object
dtypes: float64(4), int64(9), object(39)
memory usage: 6.7+ MB

In [5]:
#Visualizo las dimensiones del set
train.shape

(16947, 52)

In [6]:
#Vemos una porcion del mismo
train.head().T

,0,1,2,3,4
ID,27761,27760,27446,16808,16805
Region,EMEA,EMEA,Americas,Americas,Americas
Territory,None,None,NW America,NW America,NW America
"Pricing, Delivery_Terms_Quote_Appr",1,0,0,1,1
"Pricing, Delivery_Terms_Approved",1,0,0,0,0
Bureaucratic_Code_0_Approval,1,0,0,1,1
Bureaucratic_Code_0_Approved,1,0,0,0,0
Submitted_for_Approval,0,0,0,0,0
Bureaucratic_Code,Bureaucratic_Code_4,Bureaucratic_Code_4,Bureaucratic_Code_4,Bureaucratic_Code_5,Bureaucratic_Code_5
Account_Created_Date,6/16/2015,6/16/2015,4/21/2015,7/27/2013,7/27/2013
Source,None,None,Source_7,Source_11,Source_11
Billing_Country,Netherlands,Netherlands,United States,United States,United States
Account_Name,Account_Name_619,Account_Name_619,Account_Name_1794,Account_Name_1201,Account_Name_1201
Opportunity_Name,Opportunity_Name_12598,Opportunity_Name_12600,Opportunity_Name_469,Opportunity_Name_415,Opportunity_Name_851
Opportunity_ID,0,1,2,3,4
Sales_Contract_No,None,39,760,None,None
Account_Owner,Person_Name_51,Person_Name_51,Person_Name_64,Person_Name_8,Person_Name_8
Opportunity_Owner,Person_Name_18,Person_Name_20,Person_Name_8,Person_Name_8,Person_Name_8
Account_Type,Account_Type_2,Account_Type_2,Account_Type_5,Account_Type_5,Account_Type_5
Opportunity_Type,Opportunity_Type_1,Opportunity_Type_1,Opportunity_Type_1,Opportunity_Type_19,Opportunity_Type_19
Quote_Type,Non Binding,Non Binding,Non Binding,Non Binding,Non Binding
Delivery_Terms,Delivery_Terms_2,Delivery_Terms_2,Delivery_Terms_4,Delivery_Terms_1,Delivery_Terms_1
Opportunity_Created_Date,12/7/2015,12/7/2015,12/8/2015,12/8/2015,12/8/2015
Brand,None,None,None,Other,Other
Product_Type,None,None,None,Product_Type_0,Product_Type_0
Size,None,None,None,Size_4,Size_4
Product_Category_B,None,None,None,Product_Category_B_16,Product_Category_B_16
Price,None,None,None,0.42,0.42
Currency,None,None,None,USD,USD
Last_Activity,NaT,NaT,NaT,NaT,NaT
Quote_Expiry_Date,1/30/2016,1/20/2016,9/30/2016,NaT,6/2/2017
Last_Modified_Date,6/13/2016,1/15/2016,9/29/2016,3/27/2018,3/27/2018
Last_Modified_By,Person_Name_18,Person_Name_20,Person_Name_8,Person_Name_8,Person_Name_8
Product_Family,Product_Family_77,Product_Family_77,Product_Family_81,Product_Family_209,Product_Family_209
Product_Name,Product_Name_99,Product_Name_100,Product_Name_91,Product_Name_432,Product_Name_432
ASP_Currency,EUR,EUR,USD,USD,USD
ASP,0.52,0.53,0.48,0.53,0.53
ASP_(converted)_Currency,USD,USD,USD,USD,USD
ASP_(converted),0.59,0.60,0.48,0.53,0.53
Planned_Delivery_Start_Date,5/1/2016,1/18/2016,1/25/2016,2/1/2018,2/1/2018
Planned_Delivery_End_Date,6/30/2016,1/20/2016,1/25/2016,3/31/2018,2/28/2018
Month,2016 - 5,2016 - 1,2016 - 1,2018 - 2,2018 - 2
Delivery_Quarter,Q2,Q1,Q1,Q1,Q1
Delivery_Year,2016,2016,2016,2018,2018
Actual_Delivery_Date,NaT,NaT,NaT,NaT,NaT
TRF,10,0,0,14,25
Total_Amount_Currency,EUR,EUR,USD,USD,USD
Total_Amount,"5,272,800.00","48,230.00","83,865.60","7,421,881.50","13,357,192.50"
Total_Taxable_Amount_Currency,EUR,EUR,USD,USD,USD
Total_Taxable_Amount,"5,272,800.00","48,230.00","83,865.60","7,421,881.50","13,357,192.50"
Stage,Closed Lost,Closed Won,Closed Won,Closed Lost,Closed Lost
Prod_Category_A,Prod_Category_A_None,Prod_Category_A_None,Prod_Category_A_None,Prod_Category_A_None,Prod_Category_A_None

In [7]:
#Exploramos los tipos de datos
train.dtypes

ID                                      int64
Region                                 object
Territory                              object
Pricing, Delivery_Terms_Quote_Appr      int64
Pricing, Delivery_Terms_Approved        int64
Bureaucratic_Code_0_Approval            int64
Bureaucratic_Code_0_Approved            int64
Submitted_for_Approval                  int64
Bureaucratic_Code                      object
Account_Created_Date                   object
Source                                 object
Billing_Country                        object
Account_Name                           object
Opportunity_Name                       object
Opportunity_ID                          int64
Sales_Contract_No                      object
Account_Owner                          object
Opportunity_Owner                      object
Account_Type                           object
Opportunity_Type                       object
Quote_Type                             object
Delivery_Terms                         object
Opportunity_Created_Date               object
Brand                                  object
Product_Type                           object
Size                                   object
Product_Category_B                     object
Price                                  object
Currency                               object
Last_Activity                          object
Quote_Expiry_Date                      object
Last_Modified_Date                     object
Last_Modified_By                       object
Product_Family                         object
Product_Name                           object
ASP_Currency                           object
ASP                                   float64
ASP_(converted)_Currency               object
ASP_(converted)                       float64
Planned_Delivery_Start_Date            object
Planned_Delivery_End_Date              object
Month                                  object
Delivery_Quarter                       object
Delivery_Year                           int64
Actual_Delivery_Date                   object
TRF                                     int64
Total_Amount_Currency                  object
Total_Amount                          float64
Total_Taxable_Amount_Currency          object
Total_Taxable_Amount                  float64
Stage                                  object
Prod_Category_A                        object
dtype: object

In [8]:
#Vemos la cantidad de tipos de datos 
train.dtypes.value_counts()

object     39
int64       9
float64     4
dtype: int64

In [9]:
#Vemos la cantidad de valores nulos en cada columna del set de datos
train.isnull().sum()

ID                                       0
Region                                   0
Territory                                0
Pricing, Delivery_Terms_Quote_Appr       0
Pricing, Delivery_Terms_Approved         0
Bureaucratic_Code_0_Approval             0
Bureaucratic_Code_0_Approved             0
Submitted_for_Approval                   0
Bureaucratic_Code                        0
Account_Created_Date                     0
Source                                   0
Billing_Country                          0
Account_Name                             0
Opportunity_Name                         0
Opportunity_ID                           0
Sales_Contract_No                        0
Account_Owner                            0
Opportunity_Owner                        0
Account_Type                             0
Opportunity_Type                         0
Quote_Type                               0
Delivery_Terms                           0
Opportunity_Created_Date                 0
Brand                                    0
Product_Type                             0
Size                                     0
Product_Category_B                       0
Price                                    0
Currency                                 0
Last_Activity                            0
Quote_Expiry_Date                        0
Last_Modified_Date                       0
Last_Modified_By                         0
Product_Family                           0
Product_Name                             0
ASP_Currency                             0
ASP                                   3209
ASP_(converted)_Currency                 0
ASP_(converted)                       3209
Planned_Delivery_Start_Date              0
Planned_Delivery_End_Date                0
Month                                    0
Delivery_Quarter                         0
Delivery_Year                            0
Actual_Delivery_Date                     0
TRF                                      0
Total_Amount_Currency                    0
Total_Amount                            59
Total_Taxable_Amount_Currency            0
Total_Taxable_Amount                     0
Stage                                    0
Prod_Category_A                          0
dtype: int64

In [10]:
#Inspeccionamos las columnas del data frame con mas detalle,en particular datos de tipo numerio ,categorico y object
train.describe(include=[np.int64,np.float64,np.object, pd.Categorical]).T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ID,"16,947.00",NaN,NaN,NaN,"17,666.65","6,940.86","4,854.00","11,953.00","18,114.00","23,845.50","28,773.00"
Region,16947,5,Japan,4892,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Territory,16947,76,None,4999,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Pricing, Delivery_Terms_Quote_Appr","16,947.00",NaN,NaN,NaN,0.81,0.39,0.00,1.00,1.00,1.00,1.00
"Pricing, Delivery_Terms_Approved","16,947.00",NaN,NaN,NaN,0.58,0.49,0.00,0.00,1.00,1.00,1.00
Bureaucratic_Code_0_Approval,"16,947.00",NaN,NaN,NaN,0.48,0.50,0.00,0.00,0.00,1.00,1.00
Bureaucratic_Code_0_Approved,"16,947.00",NaN,NaN,NaN,0.32,0.47,0.00,0.00,0.00,1.00,1.00
Submitted_for_Approval,"16,947.00",NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Bureaucratic_Code,16947,7,Bureaucratic_Code_4,12587,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Account_Created_Date,16947,809,4/20/2015,3011,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Source,16947,14,None,9497,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Billing_Country,16947,80,Japan,4879,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Account_Name,16947,1635,Account_Name_1888,2124,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Opportunity_Name,16947,9841,Opportunity_Name_5036,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Opportunity_ID,"16,947.00",NaN,NaN,NaN,"5,335.94","3,324.72",0.00,"2,448.50","5,306.00","7,698.00","12,803.00"
Sales_Contract_No,16947,5267,None,6973,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Account_Owner,16947,48,Person_Name_50,3730,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Opportunity_Owner,16947,53,Person_Name_50,3781,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Account_Type,16947,7,Account_Type_2,8832,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Opportunity_Type,16947,25,Opportunity_Type_1,6819,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quote_Type,16947,2,Non Binding,16777,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delivery_Terms,16947,9,Delivery_Terms_4,7712,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Opportunity_Created_Date,16947,1096,6/30/2017,124,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brand,16947,26,None,15911,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product_Type,16947,7,None,15935,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Size,16947,7,None,15967,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product_Category_B,16947,28,None,15928,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Price,16947,53,None,15982,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Currency,16947,3,None,16052,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Last_Activity,16947,1,NaT,16947,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quote_Expiry_Date,16947,1003,NaT,4625,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Last_Modified_Date,16947,650,2/8/2018,5821,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Last_Modified_By,16947,55,Person_Name_47,8515,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product_Family,16947,227,Product_Family_77,1345,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product_Name,16947,456,Product_Name_100,976,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ASP_Currency,16947,5,USD,7361,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ASP,"13,738.00",NaN,NaN,NaN,7.01,18.86,0.00,0.36,0.40,0.51,80.00
ASP_(converted)_Currency,16947,1,USD,16947,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ASP_(converted),"13,738.00",NaN,NaN,NaN,0.43,0.76,0.00,0.37,0.41,0.48,67.00
Planned_Delivery_Start_Date,16947,986,3/31/2016,381,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Planned_Delivery_End_Date,16947,1017,3/31/2016,451,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Month,16947,53,2018 - 10,666,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delivery_Quarter,16947,4,Q2,4443,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delivery_Year,"16,947.00",NaN,NaN,NaN,"2,017.14",0.83,"2,016.00","2,016.00","2,017.00","2,018.00","2,020.00"
Actual_Delivery_Date,16947,1,NaT,16947,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TRF,"16,947.00",NaN,NaN,NaN,2.34,12.17,0.00,0.00,0.00,1.00,500.00
Total_Amount_Currency,16947,5,USD,7361,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total_Amount,"16,888.00",NaN,NaN,NaN,"1,993,659.22","18,484,259.88",0.00,"26,775.00","107,250.00","460,389.83","1,320,000,000.00"
Total_Taxable_Amount_Currency,16947,5,USD,7347,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total_Taxable_Amount,"16,947.00",NaN,NaN,NaN,"3,224,116.79","20,303,604.73",0.00,"85,465.80","376,067.25","1,037,450.00","1,356,338,620.00"
Stage,16947,5,Closed Won,9533,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Prod_Category_A,16947,1,Prod_Category_A_None,16947,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#Viendo que hay columnas de tipo int64 ,analizamos si estas pueden optimizarse cambiando el formato
train["ID"].max()

28773

In [12]:
train["Pricing, Delivery_Terms_Quote_Appr"].max()

1

In [13]:
train["Pricing, Delivery_Terms_Approved"].max()

1

In [14]:
train["Submitted_for_Approval"].max()

0

In [15]:
#Observamos que varias columnas pueden optimizarse cambiando sus tipos de datos para lograr un menor uso de la memoria
#al momento de cargar el set de datos.
#Creamos ademas una funcion de carga del dataframe para usar en general en cada analisis exploratorio
#(ver en cargar_df.ipynb)
train2=get_train()

In [16]:
#Visualizamos ahora con la funcion de carga, los tipos de datos modificados y su consumo de memoria
train2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16947 entries, 0 to 16946
Data columns (total 52 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  16947 non-null  int16
 1   Region                              16947 non-null  category
 2   Territory                           16947 non-null  category
 3   Pricing, Delivery_Terms_Quote_Appr  16947 non-null  int16
 4   Pricing, Delivery_Terms_Approved    16947 non-null  int16
 5   Bureaucratic_Code_0_Approval        16947 non-null  category
 6   Bureaucratic_Code_0_Approved        16947 non-null  category
 7   Submitted_for_Approval              16947 non-null  int16
 8   Bureaucratic_Code                   16947 non-null  category
 9   Account_Created_Date                16947 non-null  datetime64[ns]
 10  Source                              16947 non-null  object
 11  Billing_Country                     16947 non-null  category
 12  Account_Name                        16947 non-null  object
 13  Opportunity_Name                    16947 non-null  object
 14  Opportunity_ID                      16947 non-null  int64
 15  Sales_Contract_No                   16947 non-null  object
 16  Account_Owner                       16947 non-null  category
 17  Opportunity_Owner                   16947 non-null  category
 18  Account_Type                        16947 non-null  category
 19  Opportunity_Type                    16947 non-null  category
 20  Quote_Type                          16947 non-null  category
 21  Delivery_Terms                      16947 non-null  category
 22  Opportunity_Created_Date            16947 non-null  datetime64[ns]
 23  Brand                               16947 non-null  category
 24  Product_Type                        16947 non-null  category
 25  Size                                16947 non-null  category
 26  Product_Category_B                  16947 non-null  category
 27  Price                               16947 non-null  category
 28  Currency                            16947 non-null  category
 29  Last_Activity                       16947 non-null  object
 30  Quote_Expiry_Date                   16947 non-null  object
 31  Last_Modified_Date                  16947 non-null  datetime64[ns]
 32  Last_Modified_By                    16947 non-null  object
 33  Product_Family                      16947 non-null  object
 34  Product_Name                        16947 non-null  object
 35  ASP_Currency                        16947 non-null  category
 36  ASP                                 13738 non-null  float64
 37  ASP_(converted)_Currency            16947 non-null  object
 38  ASP_(converted)                     13738 non-null  float64
 39  Planned_Delivery_Start_Date         16947 non-null  datetime64[ns]
 40  Planned_Delivery_End_Date           16872 non-null  datetime64[ns]
 41  Month                               16947 non-null  datetime64[ns]
 42  Delivery_Quarter                    16947 non-null  category
 43  Delivery_Year                       16947 non-null  int16
 44  Actual_Delivery_Date                16947 non-null  object
 45  TRF                                 16947 non-null  int64
 46  Total_Amount_Currency               16947 non-null  category
 47  Total_Amount                        16888 non-null  float64
 48  Total_Taxable_Amount_Currency       16947 non-null  category
 49  Total_Taxable_Amount                16947 non-null  float64
 50  Stage                               16947 non-null  category
 51  Prod_Category_A                     16947 non-null  category
dtypes: category(24), datetime64[ns](6), float64(4), int16(5), int64(2), object(11)
memory usage: 3.5+ MB

In [17]:
train["Stage"].value_counts()

Closed Won       9533
Closed Lost      7350
Proposal           35
Negotiation        18
Qualification      11
Name: Stage, dtype: int64

In [18]:
train["Territory"].value_counts()

None              4999
Germany           1682
NW America        1568
Australia         1208
India              809
                  ...
Egypt                1
Monaco               1
Czech Republic       1
Georgia              1
Slovenia             1
Name: Territory, Length: 76, dtype: int64

In [19]:
train["Region"].value_counts()

Japan          4892
EMEA           4664
Americas       3945
APAC           3262
Middle East     184
Name: Region, dtype: int64

In [20]:
train2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16947 entries, 0 to 16946
Data columns (total 52 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  16947 non-null  int16
 1   Region                              16947 non-null  category
 2   Territory                           16947 non-null  category
 3   Pricing, Delivery_Terms_Quote_Appr  16947 non-null  int16
 4   Pricing, Delivery_Terms_Approved    16947 non-null  int16
 5   Bureaucratic_Code_0_Approval        16947 non-null  category
 6   Bureaucratic_Code_0_Approved        16947 non-null  category
 7   Submitted_for_Approval              16947 non-null  int16
 8   Bureaucratic_Code                   16947 non-null  category
 9   Account_Created_Date                16947 non-null  datetime64[ns]
 10  Source                              16947 non-null  object
 11  Billing_Country                     16947 non-null  category
 12  Account_Name                        16947 non-null  object
 13  Opportunity_Name                    16947 non-null  object
 14  Opportunity_ID                      16947 non-null  int64
 15  Sales_Contract_No                   16947 non-null  object
 16  Account_Owner                       16947 non-null  category
 17  Opportunity_Owner                   16947 non-null  category
 18  Account_Type                        16947 non-null  category
 19  Opportunity_Type                    16947 non-null  category
 20  Quote_Type                          16947 non-null  category
 21  Delivery_Terms                      16947 non-null  category
 22  Opportunity_Created_Date            16947 non-null  datetime64[ns]
 23  Brand                               16947 non-null  category
 24  Product_Type                        16947 non-null  category
 25  Size                                16947 non-null  category
 26  Product_Category_B                  16947 non-null  category
 27  Price                               16947 non-null  category
 28  Currency                            16947 non-null  category
 29  Last_Activity                       16947 non-null  object
 30  Quote_Expiry_Date                   16947 non-null  object
 31  Last_Modified_Date                  16947 non-null  datetime64[ns]
 32  Last_Modified_By                    16947 non-null  object
 33  Product_Family                      16947 non-null  object
 34  Product_Name                        16947 non-null  object
 35  ASP_Currency                        16947 non-null  category
 36  ASP                                 13738 non-null  float64
 37  ASP_(converted)_Currency            16947 non-null  object
 38  ASP_(converted)                     13738 non-null  float64
 39  Planned_Delivery_Start_Date         16947 non-null  datetime64[ns]
 40  Planned_Delivery_End_Date           16872 non-null  datetime64[ns]
 41  Month                               16947 non-null  datetime64[ns]
 42  Delivery_Quarter                    16947 non-null  category
 43  Delivery_Year                       16947 non-null  int16
 44  Actual_Delivery_Date                16947 non-null  object
 45  TRF                                 16947 non-null  int64
 46  Total_Amount_Currency               16947 non-null  category
 47  Total_Amount                        16888 non-null  float64
 48  Total_Taxable_Amount_Currency       16947 non-null  category
 49  Total_Taxable_Amount                16947 non-null  float64
 50  Stage                               16947 non-null  category
 51  Prod_Category_A                     16947 non-null  category
dtypes: category(24), datetime64[ns](6), float64(4), int16(5), int64(2), object(11)
memory usage: 3.5+ MB